---
- name: Deploy and Register Application
  hosts: all
  tasks:
    - name: Clone the application repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ app_path }}"
        version: HEAD

    - name: Copy application files
      ansible.windows.win_copy:
        src: "{{ app_path }}\\app.exe"
        dest: "{{ app_path }}\\app.exe"

    - name: Register application as a service
      ansible.windows.win_service:
        name: "{{ site_name }}"
        path: "{{ app_path }}\\app.exe"
        start_mode: auto
        state: started
