---
- name: Install and configure wmi_exporter
  hosts: windows
  roles:
    - role: wmi_exporter
    - role: manage_services
      vars:
        service_name: "windows_exporter"
      tags: 
        - start