---
- name: Install ClamAV on Debian-based systems
  apt:
    name: clamav
    state: present
  when: ansible_os_family == "Debian"

- name: Install ClamAV on RedHat-based systems
  yum:
    name: clamav
    state: present
  when: ansible_os_family == "RedHat"
