---
- name: Install packages using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
  loop: "{{ packages }}"
