site_name: "ProdWebsite"
site_path: "C:\\inetpub\\wwwroot"
site_hostname: "prod.local"
site_port: "80"
app_path: "C:\\prod\\app"
git_repo: "https://github.com/yourusername/prod-app-repo.git"
prometheus_server: "prometheus.local"
email_recipient: "test_admin@example.com"
smtp_server: "smtp.test.example.com"